/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package distributed.main;

/**
 *
 * @author kiefer
 */
public class AboutDialog extends javax.swing.JDialog {

    /**
     * Creates new form tDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
            String htmltext =
                    "<html><b>Autoren<b>"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"2\">"
                    + "	<tr>"
                    + "		<td style=\"padding-right:10px\">Matthias Kiefer</td>"
                    + "		<td>kiefermatthias@gmail.com</td>"
                    + "	</tr>"
                    + "	<tr>"
                    + "		<td style=\"padding-right:10px\">Matthias Kiefer</td>"
                    + "		<td>kiefermatthias@gmail.com</td>"
                    + "	</tr>"
                    + "	<tr>"
                    + "		<td style=\"padding-right:10px\">Matthias Kiefer</td>"
                    + "		<td>kiefermatthias@gmail.com</td>"
                    + "	</tr>"
                    + "	<tr>"
                    + "		<td style=\"padding-right:10px\">Matthias Kiefer</td>"
                    + "		<td>kiefermatthias@gmail.com</td>"
                    + "	</tr>"
                    + "	<tr>"
                    + "		<td style=\"padding-right:10px\">Matthias Kiefer</td>"
                    + "		<td>kiefermatthias@gmail.com</td>"
                    + "	</tr>"
                    + "	<tr>"
                    + "		<td style=\"padding-right:10px\">Matthias Kiefer</td>"
                    + "		<td>kiefermatthias@gmail.com</td>"
                    + "	</tr>"
                    + "</table>"
                    + "</html>";

            
            
            jLabel1.setText(htmltext);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonButton.setText("OK");
        jButtonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonButtonMouseClicked(evt);
            }
        });
        jButtonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonButtonActionPerformed(evt);
            }
        });
        jButtonButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonButtonKeyPressed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 307, Short.MAX_VALUE)
                        .addComponent(jButtonButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtonButtonMouseClicked

    private void jButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonButtonActionPerformed

    private void jButtonButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonButtonKeyPressed

    }//GEN-LAST:event_jButtonButtonKeyPressed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
